services:
  flybox-dev:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    working_dir: /app
    command: node --inspect=0.0.0.0:9229 server/server.js
    volumes:
      - ..:/app # mount entire project root for live dev
    env_file:
      - ../../.env
    ports:
      - "${PORT:-3000}:3000" # backend API
      - "9229:9229" # Node debugger
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: zane
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
