# prod
services:
  flybox-prod:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    working_dir: /app
    env_file:
      - ../../.env
    ports:
      - "3000:3000"
    command: ["node", "server/server.js"]
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: flybox_user
      POSTGRES_PASSWORD: "Q4TuZeEWBez26xOTNjNaynkfTDAaDk8a"
      POSTGRES_DB: flybox
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
